
language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode14.2
  - os: linux
    dist: focal
    services: docker
    arch: amd64
  - os: linux
    dist: focal
    services: docker
    arch: arm64

addons:
  homebrew:
    update: false

#https://github.com/travis-ci/travis-ci/issues/6893
if: tag IS present

# prevent duplicate builds on tagged versions on master
# development to be done on other branches
branches:
  except:
    - main

# please see this if you have issues in docker with utf8_py3.out
#https://stackoverflow.com/questions/29740662/python3-utf8-codecs-not-decoding-as-expected-in-docker-ubuntutrusty

#before_install:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#    sudo apt-get install tcl8.5 tcl8.5-dev tcl-dev python3 python3-dev cmake flex bison;
#    fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#    (curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh  &&
#     bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/anaconda &&
#     ${HOME}/anaconda/bin/conda create -y --name python37 python=3.7
#    );
#    fi

#script:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#    (bash scripts/setup_ubuntu_18.sh && cd linux_x86_64_release && make -j2 && ctest --verbose);
#    fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#    (bash scripts/setup_osx_anaconda.sh && cd osx_release && make -j2 && ctest --verbose);
#    fi

before_script:
  - export HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install cmake;
      /usr/local/bin/pip3 install --upgrade pip;
    fi
  # specifically for pypi deployment
  - export README_BASE_URL="https://github.com/devsim/symdiff/blob/${TRAVIS_TAG}"

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./scripts/build_docker_manylinux_2_28.sh ${TRAVIS_TAG};
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./scripts/build_macos.sh "${TRAVIS_TAG}";
    fi

deploy:
  provider: releases
  api_key:
    secure: "UrKCvZVvVCY51kbF31AKQiS2LSPNCkTeFGUTuP5XIvwWuupJockT/FVJXxdlBPjc1ALQr1or2ObPvOdp3XBbcoEWRCG9pFhQOuAh3HKntC1sxitudY3Djvn9g4iwlzBVzyzJoRo9Tra2zybjcwN8Q3HdXFeHzP3A1L3uatViTiE="

  file_glob: true
  file:
    - "symdiff*.whl"
  skip_cleanup: true
  prerelease: false
  draft:      true
  # fix issue with multiple deployments https://github.com/travis-ci/travis-ci/issues/6132
  tag_name: $TRAVIS_TAG
  on:
    repo: devsim/symdiff
    tags: true

