
language: cpp

os:
  - linux
  - osx

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get install tcl8.5 tcl8.5-dev tcl-dev python2.7 python2.7-dev cmake flex bison;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    (curl -O https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh  &&
     bash Miniconda2-latest-MacOSX-x86_64.sh -b -p $HOME/anaconda
     ${HOME}/anaconda/bin/conda create -y --name python3 python=3
    );
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    (bash scripts/setup_ubuntu_14.04.sh && cd linux_x86_64_release && make -j2 && make test);
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    (bash scripts/setup_osx_anaconda.sh && cd osx_release && make -j2 && make test);
    fi


