
language: cpp

matrix:
  include:
  - os: osx
    env: COMPILER=clang
    osx_image: xcode10.1
  - os: linux
    sudo: required
    dist: trusty
    services: docker

#https://github.com/travis-ci/travis-ci/issues/6893
if: tag IS present

# prevent duplicate builds on tagged versions on master
# development to be done on other branches
branches:
  except:
    - main

# please see this if you have issues in docker with utf8_py3.out
#https://stackoverflow.com/questions/29740662/python3-utf8-codecs-not-decoding-as-expected-in-docker-ubuntutrusty

#before_install:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#    sudo apt-get install tcl8.5 tcl8.5-dev tcl-dev python3 python3-dev cmake flex bison;
#    fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#    (curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh  &&
#     bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/anaconda &&
#     ${HOME}/anaconda/bin/conda create -y --name python37 python=3.7
#    );
#    fi

#script:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#    (bash scripts/setup_ubuntu_18.sh && cd linux_x86_64_release && make -j2 && ctest --verbose);
#    fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#    (bash scripts/setup_osx_anaconda.sh && cd osx_release && make -j2 && ctest --verbose);
#    fi

#### TODO: make sure to keep ctest from above
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./scripts/build_docker_manylinux2014.sh ${TRAVIS_TAG};
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      source  ./scripts/install_miniconda_macos.sh;
      if [ "$COMPILER" == "gcc" ]; then
        ./scripts/build_macos.sh $COMPILER "${TRAVIS_TAG}";
      elif [ "$COMPILER" == "clang" ]; then
        ./scripts/build_macos.sh $COMPILER "clang_${TRAVIS_TAG}";
      fi
    fi

deploy:
  provider: releases
  api_key:
    secure: F2Cxh/mYSqsmCTsggWqD2frhUW5x94D2bl61zj2JHYyTUSU0KXyzFp8aQAaGzfyaoBlc9G5JlveozrwPFnJQK9Yh+IW5wj8yiDXA0s2hv/vhlmVQZ/PqOZBXDeHmmptnfZtRuMAFrZD/zm9BUwNi6/2czRFxn5JYKjb45SavV4Q=
  file_glob: true
  file:
    - "symdiff*.whl"
  skip_cleanup: true
  prerelease: false
  draft:      true
  # fix issue with multiple deployments https://github.com/travis-ci/travis-ci/issues/6132
  tag_name: $TRAVIS_TAG
  on:
    repo: devsim/symdiff
    tags: true

